name: markymark
description: A simple web server to preview your Markdown files.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  markdown: any
  path: any
  shelf: any
  shelf_static: any
  yaml: ^3.1.0
executables:
  markymark:
