name: markymark
description: A simple web server to preview your Markdown files.
version: 0.1.1
authors:
- munificent
- thosakwe
dependencies:
  args: ^0.13.7
  markdown: ^0.11.0
  path: ^1.0.0
  shelf: ^0.6.7+1
  shelf_static: ^0.2.4
  shelf_web_socket: ^0.2.1
executables:
  markymark:
